# -------------------------------- GENERATED BY C_BUILD --------------------------------
import os
import sys

def FIND_C_BUILD(current_dir):
    if os.path.isdir(os.path.join(current_dir, "c_build")):
        sys.path.insert(0, current_dir)
        return

    parent_dir = os.path.dirname(current_dir)
    if parent_dir != current_dir:
        FIND_C_BUILD(parent_dir)

FIND_C_BUILD(os.path.abspath(os.path.dirname(__file__)))
from c_build.source.UserUtilities import *
from c_build.source.Manager import *
# --------------------------------------------------------------------------------------

pc: ProjectConfig = ProjectConfig(
    project_name = "splc",
    project_dependencies = [
        Dependency("ckg", branch_name="CompleteRewrite"),
        Dependency("cj")
    ],
    project_debug_with_visual_studio = False,
    project_rebuild_project_dependencies = True,
    project_executable_names  = ["splc.exe ../../SPL_Source/test.spl"]
)

cc: CompilerConfig = CompilerConfig(
    compiler_name = C_BUILD_COMPILER_NAME() if C_BUILD_IS_DEPENDENCY() else "INVALID_COMPILER",
    compiler_std_version = "c11",
    compiler_warning_level = "",
    compiler_disable_specific_warnings = [""],
    compiler_treat_warnings_as_errors = True,
    compiler_disable_warnings  = False,
    compiler_disable_sanitizer = True
)

if IS_WINDOWS() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "cl"
elif IS_DARWIN() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "clang"
elif IS_LINUX() and not C_BUILD_IS_DEPENDENCY():
    cc.compiler_name = "gcc"

# Do different things depending on the platform
if cc.compiler_name == "cl":
    cc.compiler_warning_level = "4"
    cc.compiler_disable_specific_warnings = ["5105", "4668", "4820", "4996", "4189"]
else:
    cc.compiler_warning_level = "all"
    cc.compiler_disable_specific_warnings = ["deprecated", "parentheses", "missing-braces", "switch", "unused-variable", "unused-result"]

build_postfix = f"build_{cc.compiler_name}/{C_BUILD_BUILD_TYPE()}"
procedures_config = {
    "splc": ProcedureConfig(
        build_directory = f"./{build_postfix}",
        output_name = "splc.exe",
        source_files = [
            "../../Source/*.c", 
            "../../ckg/ckg.c", 
            "../../cj/cj.c"],
        compile_time_defines = [],
        compiler_inject_into_args = [],
        include_paths = [
            "../../Include", 
            "../../ckg",
            "../../cj"
        ]
    ),
}

manager: Manager = Manager(cc, pc, procedures_config)
manager.build_project()
# -------------------------------------------------------------------------------------